runtime: python39
entrypoint: gunicorn -b :$PORT final_project.wsgi
env_variables:
  SECRET_KEY: 'django-insecure-y9cz++1s8w_=^m4t7zt(--1yh*5qojq0uik6x5-6)kcy#!86%-'
  DATABASE_PASSWORD: '^KcFOd@mQ;"=[Z(6'
handlers:
- url: /static
  static_dir: static/